#include "operators.h"

// Define message operators - these are examples, modify as needed for your CAN bus messages
const message_operator_t message_operators[NUM_MESSAGE_OPERATORS] = {
    // Message 0x0A5 operators
    {
        .message_id = 0x0A5,
        .name = "ENGINE_RPM",
        .offset = 0,
        .length = 2,
        .mult_factor = 1.0,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},
    {.message_id = 0x0A5,
     .name = "ENGINE_TEMP",
     .offset = 2,
     .length = 1,
     .mult_factor = 1.0,
     .add_factor = -40.0, // Compensate for offset
     .is_signed = false,
     .bit_mode = false,
     .has_mask = false,
     .mask = 0},

    // Message 0x0D9 operators
    {
        .message_id = 0x0D9,
        .name = "VEHICLE_SPEED",
        .offset = 0,
        .length = 2,
        .mult_factor = 0.1,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},

    // Message 0x0EF operators
    {
        .message_id = 0x0EF,
        .name = "ACCELERATOR_POS",
        .offset = 0,
        .length = 1,
        .mult_factor = 0.392,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},
    {.message_id = 0x0EF,
     .name = "BRAKE_PRESSURE",
     .offset = 1,
     .length = 1,
     .mult_factor = 0.725,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = false,
     .has_mask = false,
     .mask = 0},

    // Message 0x0F3 operators
    {
        .message_id = 0x0F3,
        .name = "FUEL_LEVEL",
        .offset = 0,
        .length = 1,
        .mult_factor = 0.392,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},
    {.message_id = 0x0F3,
     .name = "FUEL_PRESSURE",
     .offset = 1,
     .length = 1,
     .mult_factor = 3.0,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = false,
     .has_mask = false,
     .mask = 0},

    // Message 0x1A1 operators
    {
        .message_id = 0x1A1,
        .name = "GEAR_POSITION",
        .offset = 0,
        .length = 1,
        .mult_factor = 1.0,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},
    {.message_id = 0x1A1,
     .name = "CLUTCH_STATUS",
     .offset = 1,
     .length = 1,
     .mult_factor = 1.0,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = true,
     .has_mask = false,
     .mask = 0},

    // Message 0x302 operators
    {
        .message_id = 0x302,
        .name = "BATTERY_VOLTAGE",
        .offset = 0,
        .length = 2,
        .mult_factor = 0.01,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = false,
        .has_mask = false,
        .mask = 0},
    {.message_id = 0x302,
     .name = "ALTERNATOR_VOLTAGE",
     .offset = 2,
     .length = 2,
     .mult_factor = 0.01,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = false,
     .has_mask = false,
     .mask = 0},

    // Additional bit-mode example with mask
    {
        .message_id = 0x0EF,
        .name = "ABS_ACTIVE",
        .offset = 12,
        .length = 1,
        .mult_factor = 1.0,
        .add_factor = 0.0,
        .is_signed = false,
        .bit_mode = true,
        .has_mask = true,
        .mask = 0x01},
    {.message_id = 0x0EF,
     .name = "TRACTION_ACTIVE",
     .offset = 13,
     .length = 1,
     .mult_factor = 1.0,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = true,
     .has_mask = true,
     .mask = 0x01},
    {.message_id = 0x0A5,
     .name = "CHECK_ENGINE",
     .offset = 24,
     .length = 1,
     .mult_factor = 1.0,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = true,
     .has_mask = true,
     .mask = 0x01},
    {.message_id = 0x0A5,
     .name = "OIL_PRESSURE",
     .offset = 3,
     .length = 1,
     .mult_factor = 4.0,
     .add_factor = 0.0,
     .is_signed = false,
     .bit_mode = false,
     .has_mask = false,
     .mask = 0}};